name: Execute notebook

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Test
      run: |
        echo $PWD
    - uses: yaananth/run-notebook@v1
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
      with:
        notebook: "test.ipynb"
        params: "params.json"
      continue-on-error: true
    - name: Dump runner context
      env:
        RUNNER: ${{ toJson(runner) }}
      run: |
        cd ${{ RUNNER.workspace }}
        ls
        cd ${{ RUNNER.temp }}
        ls
    - uses: actions/upload-artifact@master
      with:
        name: output
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}
