name: Test-nb-runner

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Dump runner context
      env:
        RUNNER: ${{ toJson(runner) }}
      run: echo "$RUNNER"
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install papermill ipykernel nbformat
    - name: Run notebook
      env:
        RUNNER: ${{ toJson(runner) }}
      run: |
        python - << "EOF"
        import papermill as pm
        pm.execute_notebook(
           'test.ipynb',
           '${{ RUNNER.temp }}/test.ipynb',
           parameters = dict(alpha=0.6, ratio=0.1)
        )
        EOF
    - name: Strip out
      env:
        RUNNER: ${{ toJson(runner) }}
      run: |
        python - << "EOF"
        from traitlets.config import Config
        import nbformat as nbf
        from nbconvert.exporters import HTMLExporter

        c = Config()

        # Configure our tag removal
        c.TagRemovePreprocessor.remove_cell_tags = ("remove_cell",)
        c.TagRemovePreprocessor.remove_input_tags = ('remove_input',)

        # Configure and run out exporter
        c.HTMLExporter.preprocessors = ["TagRemovePreprocessor"]
        HTMLExporter(config=c).from_filename('${{ RUNNER.temp }}/test.ipynb')
        EOF
     - name: Test
      env:
        RUNNER: ${{ toJson(runner) }}
      run: |
        cat '${{ RUNNER.temp }}/test.ipynb'
