name: Test-nb-runner

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Dump runner context
      env:
        RUNNER: ${{ toJson(runner) }}
      run: echo "$RUNNER"
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install papermill
        python -m pip install ipykernel
    - name: Run notebook
      env:
        RUNNER: ${{ toJson(runner) }}
      run: |
        python - << "EOF"
        import papermill as pm
        pm.execute_notebook(
           'test.ipynb',
           '${{ RUNNER.temp }}\test.ipynb',
           parameters = dict(alpha=0.6, ratio=0.1)
        )
        EOF
