name: Test-nb-runner

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install papermill
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Run notebook
      run: |
        import papermill as pm
