name: FORKTest-nb-runner

on:
  push:
    branches:
    - automation/test/*
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - uses: yaananth/run-notebook@v1
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "test.ipynb"
        params: "params.json"
      continue-on-error: true
    - uses: actions/upload-artifact@master
      with:
        name: output
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}
