name: Test-nb-runner

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install papermill
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Run notebook
      run: |
        python - << "EOF"
        import papermill as pm
        pm.execute_notebook(
           'test.ipynb',
           'test_2.ipynb',
           parameters = dict(alpha=0.6, ratio=0.1)
        )
        EOF
